package com.flowfleet.cdc;

import static org.assertj.core.api.Assertions.assertThat;
import static org.awaitility.Awaitility.await;

import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import java.time.Duration;
import java.util.List;
import java.util.Properties;
import java.util.concurrent.ConcurrentLinkedQueue;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.MethodOrderer;
import org.junit.jupiter.api.Order;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.TestMethodOrder;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;
import org.testcontainers.utility.DockerImageName;

/**
 * Exercises the real Debezium PostgreSQL connector (embedded) against a real PostgreSQL:
 * initial snapshot, then INSERT / UPDATE / DELETE captured from the WAL, with before/after
 * images and a tombstone. Methods run in order against one shared capture session.
 */
@Testcontainers
@TestMethodOrder(MethodOrderer.OrderAnnotation.class)
class PostgresCdcIT {

    @Container
    static final PostgreSQLContainer<?> PG = new PostgreSQLContainer<>(
            DockerImageName.parse("imresamu/postgis:16-3.5").asCompatibleSubstituteFor("postgres"))
            .withDatabaseName("flowfleet")
            .withUsername("flowfleet")
            .withPassword("flowfleet")
            .withCommand("postgres", "-c", "wal_level=logical",
                    "-c", "max_wal_senders=4", "-c", "max_replication_slots=4")
            .withStartupTimeout(Duration.ofMinutes(3));

    static final ConcurrentLinkedQueue<CdcRecord> EVENTS = new ConcurrentLinkedQueue<>();
    static DebeziumCdcSource source;

    @BeforeAll
    static void startCapture() throws Exception {
        sql("""
            CREATE TABLE orders (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              status TEXT NOT NULL,
              total_amount NUMERIC(12,2) NOT NULL DEFAULT 0
            )
            """);
        sql("ALTER TABLE orders REPLICA IDENTITY FULL");
        sql("INSERT INTO orders (status, total_amount) VALUES ('CREATED', 9.99)");

        Path offsets = Files.createTempFile("flowfleet-cdc-it-offsets", ".dat");
        Files.deleteIfExists(offsets);
        Properties cfg = DebeziumCdcSource.postgresConfig(
                "flowfleet-cdc-it",
                PG.getHost(), PG.getMappedPort(5432), "flowfleet", "flowfleet", "flowfleet",
                "flowfleet_it_slot", List.of("public.orders"), offsets, /* dropSlotOnStop */ true);

        source = new DebeziumCdcSource(cfg, EVENTS::add);
        source.start();
    }

    @AfterAll
    static void stopCapture() throws Exception {
        if (source != null) {
            source.close();
            source.awaitStopped(Duration.ofSeconds(20));
        }
    }

    @Test
    @Order(1)
    void initialSnapshotEmitsExistingRows() {
        await().atMost(Duration.ofSeconds(60)).untilAsserted(() ->
                assertThat(EVENTS).anySatisfy(e -> {
                    assertThat(e.op()).isEqualTo(CdcRecord.Op.READ);
                    assertThat(e.fromSnapshot()).isTrue();
                    assertThat(e.table()).isEqualTo("orders");
                    assertThat(e.after().get("status").asText()).isEqualTo("CREATED");
                }));
    }

    @Test
    @Order(2)
    void insertIsCapturedFromTheWal() throws Exception {
        sql("INSERT INTO orders (status, total_amount) VALUES ('CONFIRMED', 20.00)");

        await().atMost(Duration.ofSeconds(30)).untilAsserted(() ->
                assertThat(EVENTS).anySatisfy(e -> {
                    assertThat(e.op()).isEqualTo(CdcRecord.Op.CREATE);
                    assertThat(e.fromSnapshot()).isFalse();
                    assertThat(e.after().get("status").asText()).isEqualTo("CONFIRMED");
                    assertThat(e.lsn()).isNotNull();
                }));
    }

    @Test
    @Order(3)
    void updateCarriesBeforeAndAfter() throws Exception {
        sql("UPDATE orders SET status='DELIVERED' WHERE status='CONFIRMED'");

        await().atMost(Duration.ofSeconds(30)).untilAsserted(() ->
                assertThat(EVENTS).anySatisfy(e -> {
                    assertThat(e.op()).isEqualTo(CdcRecord.Op.UPDATE);
                    assertThat(e.before().get("status").asText()).isEqualTo("CONFIRMED");
                    assertThat(e.after().get("status").asText()).isEqualTo("DELIVERED");
                }));
    }

    @Test
    @Order(4)
    void deleteEmitsBeforeImageThenTombstone() throws Exception {
        sql("DELETE FROM orders WHERE status='DELIVERED'");

        await().atMost(Duration.ofSeconds(30)).untilAsserted(() -> {
            assertThat(EVENTS).anySatisfy(e -> {
                assertThat(e.op()).isEqualTo(CdcRecord.Op.DELETE);
                assertThat(e.after()).isNull();
                assertThat(e.before().get("status").asText()).isEqualTo("DELIVERED");
            });
            assertThat(EVENTS).anySatisfy(e -> assertThat(e.isTombstone()).isTrue());
        });
    }

    private static void sql(String statement) throws Exception {
        try (Connection c = DriverManager.getConnection(
                PG.getJdbcUrl(), PG.getUsername(), PG.getPassword());
             Statement s = c.createStatement()) {
            s.execute(statement);
        }
    }
}
