-- ============================================================================
-- FlowFleet operational schema (OLTP).
--
-- This is the source of truth that Debezium will stream from in Phase 3, so a
-- few choices are made with CDC in mind:
--   * every table has a stable surrogate BIGINT primary key (clean Kafka key);
--   * every mutable table carries updated_at (lets consumers reason about order);
--   * status columns are plain TEXT, not PG enums or CHECK lists, so adding a
--     new status later is a code change, not a locking DDL migration;
--   * updated_at is written by the application (Spring Data JDBC), with a DB
--     DEFAULT as a safety net for any out-of-band writes.
-- ============================================================================

CREATE EXTENSION IF NOT EXISTS postgis;

-- ----------------------------------------------------------------------------
-- Reference / dimension-like data
-- ----------------------------------------------------------------------------
CREATE TABLE customers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT        NOT NULL,
    email       TEXT        NOT NULL UNIQUE,
    phone       TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE vehicles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type        TEXT        NOT NULL,
    plate       TEXT        NOT NULL UNIQUE,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE restaurants (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT        NOT NULL,
    location    geometry(Point, 4326) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ----------------------------------------------------------------------------
-- Drivers & shifts
-- ----------------------------------------------------------------------------
CREATE TABLE drivers (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT        NOT NULL,
    status      TEXT        NOT NULL DEFAULT 'OFFLINE',
    vehicle_id  BIGINT      REFERENCES vehicles (id),
    version     BIGINT      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE driver_shifts (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    driver_id   BIGINT      NOT NULL REFERENCES drivers (id),
    status      TEXT        NOT NULL DEFAULT 'ACTIVE',
    started_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    ended_at    TIMESTAMPTZ
);
CREATE INDEX idx_driver_shifts_driver ON driver_shifts (driver_id);
-- at most one open shift per driver
CREATE UNIQUE INDEX uq_driver_shifts_open ON driver_shifts (driver_id) WHERE status = 'ACTIVE';

-- ----------------------------------------------------------------------------
-- Orders
-- ----------------------------------------------------------------------------
CREATE TABLE orders (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   BIGINT        NOT NULL REFERENCES customers (id),
    restaurant_id BIGINT        NOT NULL REFERENCES restaurants (id),
    status        TEXT          NOT NULL DEFAULT 'CREATED',
    total_amount  NUMERIC(12,2) NOT NULL DEFAULT 0,
    version       BIGINT        NOT NULL DEFAULT 0,
    created_at    TIMESTAMPTZ   NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ   NOT NULL DEFAULT now()
);
CREATE INDEX idx_orders_status ON orders (status);
CREATE INDEX idx_orders_customer ON orders (customer_id);
CREATE INDEX idx_orders_created_at ON orders (created_at);

CREATE TABLE order_items (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id    BIGINT        NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    name        TEXT          NOT NULL,
    quantity    INT           NOT NULL CHECK (quantity > 0),
    unit_price  NUMERIC(12,2) NOT NULL CHECK (unit_price >= 0)
);
CREATE INDEX idx_order_items_order ON order_items (order_id);

-- ----------------------------------------------------------------------------
-- Deliveries
-- ----------------------------------------------------------------------------
CREATE TABLE deliveries (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id     BIGINT      NOT NULL UNIQUE REFERENCES orders (id),
    driver_id    BIGINT      REFERENCES drivers (id),
    status       TEXT        NOT NULL DEFAULT 'PENDING',
    pickup_lat   DOUBLE PRECISION,
    pickup_lon   DOUBLE PRECISION,
    delivery_lat DOUBLE PRECISION,
    delivery_lon DOUBLE PRECISION,
    version      BIGINT      NOT NULL DEFAULT 0,
    created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_deliveries_driver ON deliveries (driver_id);
CREATE INDEX idx_deliveries_status ON deliveries (status);

-- ----------------------------------------------------------------------------
-- Geofences (PostGIS polygons)
-- ----------------------------------------------------------------------------
CREATE TABLE geofences (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT        NOT NULL,
    type        TEXT        NOT NULL,
    geom        geometry(Polygon, 4326) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_geofences_geom ON geofences USING GIST (geom);
