spring:
  application:
    name: flowfleet-location-consumer

flowfleet:
  consumer:
    group-id: ${CONSUMER_GROUP:flowfleet.location-consumer}
    topic: ${CONSUMER_TOPIC:flowfleet.driver.locations}
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:19092}
    schema-registry-url: ${SCHEMA_REGISTRY_URL:http://localhost:18085}
    auto-offset-reset: ${CONSUMER_OFFSET_RESET:earliest}
    enabled: ${CONSUMER_ENABLED:true}

server:
  port: ${SERVER_PORT:8091}
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health, info, prometheus, metrics
  endpoint:
    health:
      probes:
        enabled: true

logging:
  level:
    com.flowfleet: info
    org.apache.kafka.clients.consumer: warn
